name: Prepare Release PR (Release Please)
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [ubuntu-latest]
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # ratchet:googleapis/release-please-action@v4.2.0
        with:
          token: ${{ github.token }}
          release-type: node
