name: Prepare Release PR (Release Please)
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: [ubuntu-latest]
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # ratchet:googleapis/release-please-action@v4.4.0
        with:
          token: ${{ github.token }}
          release-type: node

  publish:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: [ubuntu-latest]
    container: node:20-bookworm
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - run: yarn npm publish
